version: '3.8'

services:
  db:
    image: postgres:15.3-alpine3.18
    restart: 'no'
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "localhost", "-p", "5432", "-U", "admin", "-d", "curso_manguinho" ]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s
    environment:
      - POSTGRES_DB=curso_manguinho
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432